name: "What's Playing?"
description: "Show what's playing..."
version: "0.0.7"
slug: "whats_playing"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
ports:
  777/tcp: 777
options:
  mqtt_username: ""
  mqtt_password: ""
  mqtt_host: "homeassistant.local"
  mqtt_port: 1884
  web_port: 777
schema:
  mqtt_username: str
  mqtt_password: str
  mqtt_host: str
  mqtt_port: int
  web_port: int
